.TH whenami 1 "1 April 2019"
.LO 1
.SH NAME
whenami \- figure out when you are
.SH SYNOPSIS
.B whenami
.RB [ \-h ]
.RB [ \-v ]
.SH DESCRIPTION
.B whenami
figures out and displays when you are.
.SH OPTIONS
No options are used for regular operation. The following options are available for alternate objectives:
.TP
.BR \-\^h " or " \-\-help
Print a help message and exit.
.TP
.BR \-\^v " or " \-\-version
Display version information and exit.
.SH EXIT STATUS
.B whenami
exits with 0 on success and 1 on errors.
.SH EXAMPLES
To figure out when you are, use:

.nf
  whenami
.fi
.SH SEE ALSO
date(1)
.SH BUGS
No known bugs.
.SH TIPS
If you have use for this program, consider seeking professional help.
.SH AUTHOR
Martin Ireblom (martin@ireblom.se)
